name: Deploy scratch2linenotify

on:
  push:
    branches: ["main"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: LLK/scratch-gui
          ref: develop
      - run: npm install
      - uses: actions/checkout@v3
        with:
          path: ./scratch2linenotify
      - run: sh ./scratch2linenotify/install.sh
      - run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      - name: npm install under scratch2linenotify
        run: npm install
        working-directory: ./scratch2linenotify
      - name: Build scratch2linenotify.mjs for xcratch
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
        working-directory: ./scratch2linenotify
      - name: Copy scratch2linenotify.mjs to build folder
        run: cp ./scratch2linenotify/dist/scratch2linenotify.mjs ./build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
